language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - "make sqlite3 deploy"
# command to run tests
script: "make test-coverage-travis-ci" #nosetests
after_success:
  - "make test-coveralls"
